mysql:
    image: mysql
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - /mnt/sda1/volumes/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=rabbit
    restart: always

redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"
    restart: always

php:
    image: rabbit52/php:7-fpm
    container_name: php
    links:
        - mysql
        - redis
    volumes:
        - ./var/log:/var/log
        - ./.composer:/root/.composer
        - ./usr/local/bin:/usr/local/bin
        - ~/htdocs:/var/htdocs
    restart: always

nginx:
    image: rabbit52/nginx
    container_name: nginx
    links:
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
        - ./etc/nginx/includes:/etc/nginx/includes
        - ./etc/nginx/sites-available:/etc/nginx/sites-available
        - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
        - ~/htdocs:/var/htdocs
        - ./var/log/nginx:/var/log/nginx
    restart: always
