mysql:
    image: mysql
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - /mnt/sda1/volumes/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: rabbit
        TZ: Asia/Chongqing
    restart: always

redis:
    image: redis
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
        - /mnt/sda1/volumes/redis:/data
        - ./etc/redis/redis.conf:/etc/redis.conf
    command: ["redis-server", "/etc/redis.conf"]
    environment:
        TZ: Asia/Chongqing
    restart: always

php:
    image: rabbit52/php:5-fpm
    container_name: php
    ports:
        - "9000:9000"
    links:
        - mysql
        - redis
    volumes:
        - ./var/log:/var/log
        - ./.composer:/root/.composer
        - ./usr/local/bin:/usr/local/bin
        - ~/htdocs:/var/htdocs
    environment:
        TZ: Asia/Chongqing
    restart: always

nginx:
    image: nginx
    container_name: nginx
    links:
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
        - ./etc/nginx/includes:/etc/nginx/includes
        - ./etc/nginx/sites:/etc/nginx/sites
        - ~/htdocs:/var/htdocs
        - ./var/log/nginx:/var/log/nginx
    environment:
        TZ: Asia/Chongqing
    restart: always
