mysql:
    image: mysql
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - d:/docker/volumes/mysql:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: rabbit
        TZ: Asia/Chongqing
    restart: always

redis:
    image: redis:alpine
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
        - d:/docker/volumes/redis:/data
        - ./etc/redis:/opt/redis
    command: ["redis-server", "/opt/redis/redis.conf"]
    environment:
        TZ: Asia/Chongqing
    restart: always

php:
    image: daocloud.io/rabbit_52/php7
    container_name: php
    links:
        - mysql
        - redis
    volumes:
        - ./var/log:/var/log
        - ./.composer:/root/.composer
        - d:/htdocs:/var/htdocs
        - d:/Dropbox/Backups/ssh:/root/ssh-outside
    working_dir: /var/htdocs
    environment:
        TZ: Asia/Chongqing
        REDIS_PORT: 6379
    restart: always

nginx:
    image: nginx:alpine
    container_name: nginx
    links:
        - php
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./etc/nginx/conf.d:/etc/nginx/conf.d
        - ./etc/nginx/includes:/etc/nginx/includes
        - ./etc/nginx/sites:/etc/nginx/sites
        - d:/htdocs:/var/htdocs
        - ./var/log/nginx:/var/log/nginx
    working_dir: /var/htdocs
    environment:
        TZ: Asia/Chongqing
    restart: always