#!/bin/sh
echo "start php-fpm..."
docker run -d\
    -p 9000:9000\
    -v $PWD/var/log:/var/log\
    -v $PWD/.composer:/root/.composer\
    -v ~/htdocs:/var/htdocs\
    -v $PWD/usr/local/bin:/usr/local/bin\
    --name php\
    rabbit52/php-fpm
