#!/bin/sh
echo "start php-fpm..."
docker run -d\
    -p 9000:9000\
    -v $PWD/var/log:/var/log\
    -v $PWD/.composer:/root/.composer\
    -v ~/htdocs:/var/htdocs\
    -v $PWD/usr/local/bin:/usr/local/bin\
    --name php-fpm\
    php-fpm

echo "start nginx..."
docker run -d\
    -p 80:80\
    -v $PWD/etc/nginx/conf.d:/etc/nginx/conf.d\
    -v $PWD/etc/nginx/includes:/etc/nginx/includes\
    -v $PWD/etc/nginx/sites-available:/etc/nginx/sites-available\
    -v $PWD/etc/nginx/sites-enabled:/etc/nginx/sites-enabled\
    -v ~/htdocs:/var/htdocs\
    -v $PWD/var/log/nginx:/var/log/nginx\
    --name nginx\
    nginx
